vostrukhin_kafka_1
IlyaVostrukhin/JavaSchool pull request #1
Opened 2024-12-30 00:56 UTC by IlyaVostrukhin

2025-01-17 06:08 UTC, Liman26 requested changes

2025-01-17 06:08 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +                .getProperty("transaction.topic");
В константы лучше вынести

2025-01-17 06:08 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +                ((recordMetadata, e) -> {
Лямбду можно в отдельный метод вынести, будет более читабельно

2025-01-21 06:10 UTC, IlyaVostrukhin commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +                .getProperty("transaction.topic");
Вынес

2025-01-21 06:10 UTC, IlyaVostrukhin commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +                ((recordMetadata, e) -> {
Вынес

2025-01-23 02:09 UTC, Liman26 approved these changes

2025-01-23 04:00 UTC, merged